spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: thinban-rest
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    #    password:
    database: 0
    lettuce:
      # redis连接池配置
      pool:
        min-idle: 1
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 5
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 5
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
  #        max-wait: 60000
  mail:
    host: smtp.163.com
    password: xxx
    port: 25
    properties:
      from: xxx@163.com
    username: xxx@163.com
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: admin
server:
  port: 8080